# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=i386-linux-gnu      -x mir -run-pass=instruction-select -verify-machineinstrs < %s -o - | FileCheck %s --check-prefix=X86
# RUN: llc -mtriple=x86_64-linux-gnux32 -x mir -run-pass=instruction-select -verify-machineinstrs < %s -o - | FileCheck %s --check-prefix=X32

--- |
  define void @foo(i32 %x) {
  entry:
    switch i32 %x, label %default [
      i32 0, label %bb0
      i32 1, label %bb1
      i32 2, label %bb2
      i32 3, label %bb3
    ]
  bb0:
    br label %exit
  bb1:
    br label %exit
  bb2:
    br label %exit
  bb3:
    br label %exit
  exit:
    ret void
  default:
    unreachable
  }
...
---
name:            foo
alignment:       16
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: gpr, preferred-register: '', flags: [  ] }
  - { id: 1, class: gpr, preferred-register: '', flags: [  ] }
  - { id: 2, class: gpr, preferred-register: '', flags: [  ] }
  - { id: 3, class: gpr, preferred-register: '', flags: [  ] }
  - { id: 4, class: gpr, preferred-register: '', flags: [  ] }
jumpTable:
  kind:            block-address
  entries:
    - id:              0
      blocks:          [ '%bb.2', '%bb.3', '%bb.4', '%bb.5' ]
body:             |
  ; X86-LABEL: name: foo
  ; X86: bb.0.entry:
  ; X86-NEXT:   successors: %bb.1(0x80000000)
  ; X86-NEXT:   liveins: $edi
  ; X86-NEXT: {{  $}}
  ; X86-NEXT:   [[COPY:%[0-9]+]]:gr32 = COPY $edi
  ; X86-NEXT:   [[SUB32ri:%[0-9]+]]:gr32 = SUB32ri [[COPY]], 0, implicit-def dead $eflags
  ; X86-NEXT:   [[COPY1:%[0-9]+]]:gr32_nosp = COPY [[SUB32ri]]
  ; X86-NEXT: {{  $}}
  ; X86-NEXT: bb.1.entry:
  ; X86-NEXT:   successors: %bb.2(0x20000000), %bb.3(0x20000000), %bb.4(0x20000000), %bb.5(0x20000000)
  ; X86-NEXT: {{  $}}
  ; X86-NEXT:   [[LEA32r:%[0-9]+]]:gr32 = LEA32r $noreg, 1, $noreg, %jump-table.0, $noreg
  ; X86-NEXT:   [[MOV32rm:%[0-9]+]]:gr32 = MOV32rm [[LEA32r]], 4, [[COPY1]], 0, $noreg
  ; X86-NEXT:   JMP32r [[MOV32rm]]
  ; X86-NEXT: {{  $}}
  ; X86-NEXT: bb.2.bb0:
  ; X86-NEXT:   successors: %bb.6(0x80000000)
  ; X86-NEXT: {{  $}}
  ; X86-NEXT:   JMP_1 %bb.6
  ; X86-NEXT: {{  $}}
  ; X86-NEXT: bb.3.bb1:
  ; X86-NEXT:   successors: %bb.6(0x80000000)
  ; X86-NEXT: {{  $}}
  ; X86-NEXT:   JMP_1 %bb.6
  ; X86-NEXT: {{  $}}
  ; X86-NEXT: bb.4.bb2:
  ; X86-NEXT:   successors: %bb.6(0x80000000)
  ; X86-NEXT: {{  $}}
  ; X86-NEXT:   JMP_1 %bb.6
  ; X86-NEXT: {{  $}}
  ; X86-NEXT: bb.5.bb3:
  ; X86-NEXT:   successors: %bb.6(0x80000000)
  ; X86-NEXT: {{  $}}
  ; X86-NEXT:   JMP_1 %bb.6
  ; X86-NEXT: {{  $}}
  ; X86-NEXT: bb.6.exit:
  ; X86-NEXT:   RET 0
  ; X86-NEXT: {{  $}}
  ; X86-NEXT: bb.7.default:
  ;
  ; X32-LABEL: name: foo
  ; X32: bb.0.entry:
  ; X32-NEXT:   successors: %bb.1(0x80000000)
  ; X32-NEXT:   liveins: $edi
  ; X32-NEXT: {{  $}}
  ; X32-NEXT:   [[COPY:%[0-9]+]]:gr32 = COPY $edi
  ; X32-NEXT:   [[SUB32ri:%[0-9]+]]:gr32 = SUB32ri [[COPY]], 0, implicit-def dead $eflags
  ; X32-NEXT:   [[COPY1:%[0-9]+]]:gr32_nosp = COPY [[SUB32ri]]
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.1.entry:
  ; X32-NEXT:   successors: %bb.2(0x20000000), %bb.3(0x20000000), %bb.4(0x20000000), %bb.5(0x20000000)
  ; X32-NEXT: {{  $}}
  ; X32-NEXT:   [[LEA64_32r:%[0-9]+]]:gr32 = LEA64_32r $noreg, 1, $noreg, %jump-table.0, $noreg
  ; X32-NEXT:   [[MOV32rm:%[0-9]+]]:gr32 = MOV32rm [[LEA64_32r]], 4, [[COPY1]], 0, $noreg
  ; X32-NEXT:   JMP32r [[MOV32rm]]
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.2.bb0:
  ; X32-NEXT:   successors: %bb.6(0x80000000)
  ; X32-NEXT: {{  $}}
  ; X32-NEXT:   JMP_1 %bb.6
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.3.bb1:
  ; X32-NEXT:   successors: %bb.6(0x80000000)
  ; X32-NEXT: {{  $}}
  ; X32-NEXT:   JMP_1 %bb.6
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.4.bb2:
  ; X32-NEXT:   successors: %bb.6(0x80000000)
  ; X32-NEXT: {{  $}}
  ; X32-NEXT:   JMP_1 %bb.6
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.5.bb3:
  ; X32-NEXT:   successors: %bb.6(0x80000000)
  ; X32-NEXT: {{  $}}
  ; X32-NEXT:   JMP_1 %bb.6
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.6.exit:
  ; X32-NEXT:   RET 0
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.7.default:
  bb.1.entry:
    successors: %bb.8(0x80000000)
    liveins: $edi

    %0:gpr(s32) = COPY $edi
    %1:gpr(s32) = G_CONSTANT i32 0
    %2:gpr(s32) = G_SUB %0, %1
    %3:gpr(s32) = COPY %2(s32)

  bb.8.entry:
    successors: %bb.2(0x20000000), %bb.3(0x20000000), %bb.4(0x20000000), %bb.5(0x20000000)

    %4:gpr(p0) = G_JUMP_TABLE %jump-table.0
    G_BRJT %4(p0), %jump-table.0, %3(s32)

  bb.2.bb0:
    successors: %bb.6(0x80000000)

    G_BR %bb.6

  bb.3.bb1:
    successors: %bb.6(0x80000000)

    G_BR %bb.6

  bb.4.bb2:
    successors: %bb.6(0x80000000)

    G_BR %bb.6

  bb.5.bb3:
    successors: %bb.6(0x80000000)

    G_BR %bb.6

  bb.6.exit:
    RET 0

  bb.7.default:
...
