# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=x86_64-linux-gnu -x mir -run-pass=instruction-select -verify-machineinstrs < %s -o - | FileCheck %s

--- |
  define void @foo(i64 %x) {
  entry:
    switch i64 %x, label %default [
      i64 0, label %bb0
      i64 1, label %bb1
      i64 2, label %bb2
      i64 3, label %bb3
    ]
  bb0:
    br label %exit
  bb1:
    br label %exit
  bb2:
    br label %exit
  bb3:
    br label %exit
  exit:
    ret void
  default:
    unreachable
  }
...
---
name:            foo
alignment:       16
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: gpr, preferred-register: '', flags: [  ] }
  - { id: 1, class: gpr, preferred-register: '', flags: [  ] }
  - { id: 2, class: gpr, preferred-register: '', flags: [  ] }
  - { id: 3, class: gpr, preferred-register: '', flags: [  ] }
  - { id: 4, class: gpr, preferred-register: '', flags: [  ] }
jumpTable:
  kind:            block-address
  entries:
    - id:              0
      blocks:          [ '%bb.2', '%bb.3', '%bb.4', '%bb.5' ]
body:             |
  ; CHECK-LABEL: name: foo
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $rdi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr64 = COPY $rdi
  ; CHECK-NEXT:   [[SUB64ri32_:%[0-9]+]]:gr64 = SUB64ri32 [[COPY]], 0, implicit-def dead $eflags
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gr64_nosp = COPY [[SUB64ri32_]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x20000000), %bb.3(0x20000000), %bb.4(0x20000000), %bb.5(0x20000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LEA64r:%[0-9]+]]:gr64 = LEA64r $noreg, 1, $noreg, %jump-table.0, $noreg
  ; CHECK-NEXT:   [[MOV64rm:%[0-9]+]]:gr64 = MOV64rm [[LEA64r]], 8, [[COPY1]], 0, $noreg
  ; CHECK-NEXT:   JMP64r [[MOV64rm]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.bb0:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JMP_1 %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.bb1:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JMP_1 %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.bb2:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JMP_1 %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.bb3:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JMP_1 %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6.exit:
  ; CHECK-NEXT:   RET 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7.default:
  bb.1.entry:
    successors: %bb.8(0x80000000)
    liveins: $rdi

    %0:gpr(s64) = COPY $rdi
    %1:gpr(s64) = G_CONSTANT i64 0
    %2:gpr(s64) = G_SUB %0, %1
    %3:gpr(s64) = COPY %2(s64)

  bb.8.entry:
    successors: %bb.2(0x20000000), %bb.3(0x20000000), %bb.4(0x20000000), %bb.5(0x20000000)

    %4:gpr(p0) = G_JUMP_TABLE %jump-table.0
    G_BRJT %4(p0), %jump-table.0, %3(s64)

  bb.2.bb0:
    successors: %bb.6(0x80000000)

    G_BR %bb.6

  bb.3.bb1:
    successors: %bb.6(0x80000000)

    G_BR %bb.6

  bb.4.bb2:
    successors: %bb.6(0x80000000)

    G_BR %bb.6

  bb.5.bb3:
    successors: %bb.6(0x80000000)

    G_BR %bb.6

  bb.6.exit:
    RET 0

  bb.7.default:
...
